mv dttgr1.f dtg1.f
mv dttgr1p.f dtgp.f
mv dttgr2.f dtg2.f
mv dttgr3.f dtg3.f
mv dttgr4.f dtg4.f
mv dttgr5.f dtg5.f
mv dttgr6.f dtg6.f
mv ttgr1.f ttg1.f
mv ttgr1p.f ttgp.f
mv ttgr2.f ttg2.f
mv ttgr3.f ttg3.f
mv ttgr4.f ttg4.f
mv ttgr5.f ttg5.f
mv ttgr6.f ttg6.f
