name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macos-latest] # ubuntu-latest
        os: [macos-11] # [macos-11, ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3

      - name: Setup GNU Fortran
        uses: modflowpy/install-gfortran-action@v1
        id: macos-setup-fortran
        if: runner.os == 'macOS'

      # - name: Symlink gfortran (macOS)
      #   if: runner.os == 'macOS'
      #   run: |
      #     # make sure gfortran is available
      #     # https://github.com/actions/virtual-environments/issues/2524
      #     # https://github.com/cbg-ethz/dce/blob/master/.github/workflows/pkgdown.yaml
      #     sudo ln -s /usr/local/bin/gfortran-12 /usr/local/bin/gfortran
      #     sudo mkdir /usr/local/gfortran
      #     sudo ln -s /usr/local/Cellar/gcc@12/*/lib/gcc/12 /usr/local/gfortran/lib
      #     gfortran --version

      - name: Build and test wheels
        uses: pypa/cibuildwheel@v2.12.1

      - name: Archive wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheelhouse
          path: |
            wheelhouse

  #     - name: Upload wheels
  #       uses: actions/upload-artifact@v3
  #       with:
  #         path: ./wheelhouse/*.whl

  # build_sdist:
  #   name: Build source distribution
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Build sdist


