name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]  # [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3

      - name: Setup GNU Fortran
        uses: modflowpy/install-gfortran-action@v1
        id: macos-setup-fortran
        if: runner.os == 'macOS'
        # with:
        #   compiler: gcc
        #   version: 11

      # - name: Install boost
      #   uses: MarkusJx/install-boost@v2.4.1
      #   id: install-boost
      #   with:
      #     boost_version: 1.76.0
      #     platform_version: 20.04

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.1
        # env:
        #   BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

      # - uses: actions/upload-artifact@v3
      #   with:
      #     path: ./wheelhouse/*.whl

